import type { EPSCode, EPSCodeOption } from './data-types'

export const epsCodesData: EPSCode[] = [
  { "Id": "CCF007", "Nombre": "COMFAMILIAR CARTAGENA" },
  { "Id": "CCF027", "Nombre": "CAJA DE COMPENSACIÓN FAMILIAR DE NARIÑO" },
  { "Id": "CCF049", "Nombre": "COMFAORIENTE" },
  { "Id": "CCF102", "Nombre": "CAJA DE COMPENSACIÓN FAMILIAR DEL CHOCÓ" },
  { "Id": "CCFC09", "Nombre": "COMFABOY" },
  { "Id": "CCFC10", "Nombre": "CCF COLSUBSIDIO" },
  { "Id": "CCFC15", "Nombre": "CCF DE CORDOBA COMFACOR EPS-S" },
  { "Id": "CCFC18", "Nombre": "CAFAM EPS REGIMEN SUBSIDIADO" },
  { "Id": "CCFC20", "Nombre": "CCF DEL CHOCO COMFACHOCO EPSS" },
  { "Id": "CCFC23", "Nombre": "CCF DE LA GUAJIRA" },
  { "Id": "CCFC24", "Nombre": "COMFAMILIAR HUILA" },
  { "Id": "CCFC27", "Nombre": "COMFAMILIAR NARIÑO" },
  { "Id": "CCFC33", "Nombre": "COMFAMILIAR SUCRE" },
  { "Id": "CCFC53", "Nombre": "COMFACUNDI" },
  { "Id": "CCFC55", "Nombre": "CAJACOPI EPS" },
  { "Id": "EAS016", "Nombre": "EMPRESAS PUBLICAS DE MEDELLIN" },
  { "Id": "EAS027", "Nombre": "FONDO DE PASIVO SOCIAL DE LOS FERROCARRILES NACIONALES" },
  { "Id": "EPS001", "Nombre": "COLMEDICA E.P.S. - ALIANSALUD" },
  { "Id": "EPS002", "Nombre": "SALUD TOTAL S.A. E.P.S." },
  { "Id": "EPS005", "Nombre": "E.P.S. SANITAS S.A." },
  { "Id": "EPS008", "Nombre": "COMPENSAR E.P.S." },
  { "Id": "EPS009", "Nombre": "E.P.S. PROGRAMA COMFENALCO ANTIOQUIA" },
  { "Id": "EPS010", "Nombre": "SUSALUD - SURA - SURAMERICANA E.P.S." },
  { "Id": "EPS012", "Nombre": "COMFENALCO VALLE E.P.S." },
  { "Id": "EPS014", "Nombre": "HUMANA - VIVIR S.A. E.P.S." },
  { "Id": "EPS015", "Nombre": "SALUD COLPATRIA E.P.S." },
  { "Id": "EPS016", "Nombre": "COOMEVA E.P.S. S.A." },
  { "Id": "EPS017", "Nombre": "E.P.S. FAMISANAR LIMITADA CAFAM-COLSUBSIDIO" },
  { "Id": "EPS018", "Nombre": "E.P.S. SERVICIO OCCIDENTAL DE SALUD S.A. S.O.S." },
  { "Id": "EPS023", "Nombre": "CRUZ BLANCA E.P.S. S.A." },
  { "Id": "EPS026", "Nombre": "SOLSALUD E.P.S. S.A." },
  { "Id": "EPS031", "Nombre": "SELVASALUD S.A. E.P.S." },
  { "Id": "EPS033", "Nombre": "SALUDVIDA S.A. E.P.S." },
  { "Id": "EPS037", "Nombre": "NUEVA EPS" },
  { "Id": "EPS039", "Nombre": "GOLDEN GROUP" },
  { "Id": "EPS040", "Nombre": "SAVIA SALUD EPS" },
  { "Id": "EPS044", "Nombre": "MEDIMAS EPS S.A.S" },
  { "Id": "EPS046", "Nombre": "FUNDACION SALUDMIA EPS" },
  { "Id": "EPS101", "Nombre": "UNISALUD" },
  { "Id": "EPS103", "Nombre": "FOSYGA - ADRES" },
  { "Id": "EPSC20", "Nombre": "EPS CAPRECOM" },
  { "Id": "EPSC22", "Nombre": "CONVIDA" },
  { "Id": "EPSC25", "Nombre": "CAPRESOCA EPS" },
  { "Id": "EPSC34", "Nombre": "CAPITAL SALUD" },
  { "Id": "EPSI05", "Nombre": "MALLAMAS EPS INDIGENA" },
  { "Id": "EPSIC1", "Nombre": "DUSAKAWI EPSI" },
  { "Id": "EPSIC2", "Nombre": "MANEXKA EPS INDIGENA" },
  { "Id": "EPSIC3", "Nombre": "ASOCIACION INDIGENA DEL CAUCA" },
  { "Id": "EPSIC4", "Nombre": "ANASWAYUU" },
  { "Id": "EPSIC5", "Nombre": "MALLAMAS" },
  { "Id": "EPSIC6", "Nombre": "PIJAOS SALUD EPSI" },
  { "Id": "ESSC02", "Nombre": "EMDISALUD" },
  { "Id": "ESSC07", "Nombre": "ASOCIACIÓN MUTUAL SER EMPRESA SOLIDARIA DE SALUD A.R.S." },
  { "Id": "ESSC18", "Nombre": "ASOCIACION MUTUAL EMPRESA SOLIDARIA DE SALUD EMSSANAR EPS" },
  { "Id": "ESSC24", "Nombre": "COOSALUD" },
  { "Id": "ESSC33", "Nombre": "COMPARTA EPS-S" },
  { "Id": "ESSC62", "Nombre": "ASMET SALUD" },
  { "Id": "ESSC76", "Nombre": "AMBUQ EPS ESS" },
  { "Id": "ESSC91", "Nombre": "ECOOPSOS" },
  { "Id": "RES011", "Nombre": "EPS UNIVERSIDAD DE ANTIOQUIA" }
]

export const epsCodeOptions: EPSCodeOption[] = epsCodesData.map(item => ({
  code: item.Id,
  name: item.Nombre
})) 