import type { OccupationDecreto, OccupationDecretoOption } from './data-types'

export const occupationsDecretoData: OccupationDecreto[] = [
    { Id: "12111", Nombre: "Físicos y Astrónomos" },
    { Id: "12112", Nombre: "Meteorólogos" },
    { Id: "12114", Nombre: "Geólogos y Geofísicos" },
    { Id: "12141", Nombre: "Ingenieros industriales y de producción" },
    { Id: "12310", Nombre: "Profesores de educación superior, de universidad, institutos, tutores universitarios." },
    { Id: "12320", Nombre: "Profesores de formación profesional" },
    { Id: "12330", Nombre: "Profesores de educación secundaria" },
    { Id: "12341", Nombre: "Profesores de educación primaria" },
    { Id: "12342", Nombre: "Profesores de primera infancia" },
    { Id: "12351", Nombre: "Especialistas en métodos pedagógicos" },
    { Id: "12352", Nombre: "Profesores de educación especial e inclusiva" },
    { Id: "12353", Nombre: "Otros profesores de idiomas" },
    { Id: "12354", Nombre: "Otros profesores de música" },
    { Id: "12355", Nombre: "Otros profesores de artes" },
    { Id: "12356", Nombre: "Instructores de tecnologías de la información" },
    { Id: "12359", Nombre: "Otros profesionales de la educación no clasificados en otros grupos primarios" },
    { Id: "12411", Nombre: "Contadores, Auditores financieros, revisor fiscal y auditor contable." },
    { Id: "12412", Nombre: "Asesores financieros de inversiones" },
    { Id: "12413", Nombre: "Analistas financieros" },
    { Id: "12421", Nombre: "Analista de gestión y organización, auditor de calidad." },
    { Id: "12422", Nombre: "Profesionales en políticas de administración" },
    { Id: "12423", Nombre: "Profesionales de gestión y de talento humano" },
    { Id: "12424", Nombre: "Profesionales en formación y desarrollo personal" },
    { Id: "12511", Nombre: "Analista de sistemas" },
    { Id: "12512", Nombre: "Desarrolladores de software" },
    { Id: "12513", Nombre: "Desarrolladores de web y multimedia" },
    { Id: "12514", Nombre: "Programadores de aplicaciones" },
    { Id: "12521", Nombre: "Diseñadores y administradores de bases de datos" },
    { Id: "12522", Nombre: "Administrador de sistemas, redes, equipos informáticos, consultor de tecnología, analista de infraestructura y sistemas." },
    { Id: "12523", Nombre: "Profesionales en redes de computadores" },
    { Id: "12611", Nombre: "Abogados" },
    { Id: "12632", Nombre: "Sociólogos, antropólogos y afines" },
    { Id: "12633", Nombre: "Filósofos historiadores y especialistas en ciencias políticas" },
    { Id: "12634", Nombre: "Psicólogos" },
    { Id: "12635", Nombre: "Profesionales del trabajo social y consejeros" },
    { Id: "12636", Nombre: "Profesionales religiosos, miembros del clero, sacerdotes, religiosos" },
    { Id: "12643", Nombre: "Traductores intérpretes y otros lingüistas" },
    { Id: "13252", Nombre: "Técnicos en documentación sanitaria (registros médicos, archivos de salud)" },
    { Id: "13253", Nombre: "Trabajadores comunitarios de salud" },
    { Id: "13255", Nombre: "Técnicos y asistente terapeutas" },
    { Id: "13321", Nombre: "Agente de seguros" },
    { Id: "13411", Nombre: "Técnicos y profesionales del nivel medio del derecho de servicios legales y afines" },
    { Id: "13412", Nombre: "Trabajadores y asistentes sociales" },
    { Id: "13413", Nombre: "Auxiliares laicos de las religiones" },
    { Id: "13511", Nombre: "Técnicos en operaciones de tecnología de la información y las comunicaciones" },
    { Id: "13512", Nombre: "Técnicos en asistencia y soporte a usuarios de la de tecnología de la información y las comunicaciones" },
    { Id: "13513", Nombre: "Técnicos en redes y sistemas de computación" },
    { Id: "13514", Nombre: "Técnicos del la web" },
    { Id: "13521", Nombre: "Técnicos de radiodifusión y grabación audiovisual" },
    { Id: "13522", Nombre: "Técnicos de ingeniería y las telecomunicaciones" },
    { Id: "14131", Nombre: "Operadores de máquinas, procesadores de texto mecanógrafos y digitadores" },
    { Id: "14132", Nombre: "Grabadores de datos" },
    { Id: "14211", Nombre: "Cajeros de oficinas de correo, cobro y pago de dinero." },
    { Id: "14311", Nombre: "Auxiliar contable, financiero y cálculo de costos." },
    { Id: "14312", Nombre: "Auxiliares de servicios estadísticos, financieros y de seguros" },
    { Id: "14313", Nombre: "Auxiliares de nóminas" },
    { Id: "15113", Nombre: "Guías de museos, galerías de arte, de turismo y afines" },
    { Id: "15161", Nombre: "Astrólogos, adivinos y trabajadores afines" },
    { Id: "15162", Nombre: "Acompañantes de personas no incluidos en otros grupos primarios" },
    { Id: "15164", Nombre: "Cuidadores de animales domésticos" },
    { Id: "15230", Nombre: "Taquillero y expendedores de boletas" },
    { Id: "15311", Nombre: "Cuidadores de niños, cuidadores de personas y hogar." },
    { Id: "15312", Nombre: "Auxiliares de maestros" },
    { Id: "15321", Nombre: "Trabajadores de cuidados personales en instituciones" },
    { Id: "15322", Nombre: "Trabajadores de cuidados personales a domicilio" },
    { Id: "15323", Nombre: "Trabajadores de los cuidados personales en servicios de salud" },
    { Id: "17352", Nombre: "Decoradores de piezas artesanales de madera" },
    { Id: "17515", Nombre: "Catadores y clasificadores de alimentos y bebidas" },
    { Id: "19411", Nombre: "Preparadores de comidas rápidas" },
    { Id: "19510", Nombre: "Vendedor ambulante de servicios tales como lustra botas, limpiador de ventanas de automóviles, mandados o recados, distribución de folletos, cuidar bienes" },
    { Id: "19520", Nombre: "Vendedor ambulante de mercancías, excluye comidas de preparación rápida." },
    { Id: "21420", Nombre: "Comerciantes al por mayor y al por menor" },
    { Id: "21420", Nombre: "Prendero" },
    { Id: "21439", Nombre: "Agente de viajes" },
    { Id: "22113", Nombre: "Químicos" },
    { Id: "22120", Nombre: "Actuarios y Estadísticos" },
    { Id: "22132", Nombre: "Agrónomos Silvicultores Zootecnistas y afines" },
    { Id: "22162", Nombre: "Arquitectos paisajistas" },
    { Id: "22165", Nombre: "Cartógrafos y topógrafos" },
    { Id: "22166", Nombre: "Diseñadores gráficos y multimedia" },
    { Id: "22230", Nombre: "Profesionales de medicina tradicional y alternativa" },
    { Id: "22250", Nombre: "Veterinarios" },
    { Id: "22431", Nombre: "Profesionales de la Publicista y la comercialización." },
    { Id: "22432", Nombre: "Profesionales de relaciones públicas" },
    { Id: "22433", Nombre: "Profesionales de ventas técnicas y médicas" },
    { Id: "22434", Nombre: "Profesionales de ventas de información y de las tecnologías y las comunicaciones" },
    { Id: "22619", Nombre: "Profesionales en derecho no clasificados en otros grupos primarios" },
    { Id: "22641", Nombre: "Autores y otros escritores" },
    { Id: "22642", Nombre: "Periodistas, comentaristas" },
    { Id: "22651", Nombre: "Escultores pintores artistas y afines" },
    { Id: "22652", Nombre: "Compositores músicos y cantantes" },
    { Id: "22653", Nombre: "Coreógrafos y bailarines" },
    { Id: "22654", Nombre: "Directores y productores de cine teatro y afines" },
    { Id: "22655", Nombre: "Actores" },
    { Id: "22656", Nombre: "Locutores de radio televisión y otros medios de comunicación" },
    { Id: "22659", Nombre: "Artistas creativos interpretativos no clasificados en otros grupos primarios (payasos magos y otros artistas no clasificados)" },
    { Id: "23118", Nombre: "Delineante y dibujantes técnicos." },
    { Id: "23254", Nombre: "Técnicos en optometría y ópticas" },
    { Id: "23315", Nombre: "Tasadores y evaluadores , evaluadores de bienes raíces." },
    { Id: "23332", Nombre: "Organizador de conferencias y eventos" },
    { Id: "23339", Nombre: "Operador turístico" },
    { Id: "23421", Nombre: "Atletas y deportistas" },
    { Id: "23422", Nombre: "Entrenadores, instructores y árbitros de actividades deportivas" },
    { Id: "23423", Nombre: "Instructores de educación física y actividades recreativas" },
    { Id: "24212", Nombre: "Receptores de apuesta y afines" },
    { Id: "24214", Nombre: "Cobradores y afines" },
    { Id: "24223", Nombre: "Telefonistas" },
    { Id: "24227", Nombre: "Entrevistadores de encuestas de investigaciones de mercado" },
    { Id: "24413", Nombre: "Codificadores de datos correctores de pruebas de imprenta y afines" },
    { Id: "25113", Nombre: "Guía de turismo" },
    { Id: "25131", Nombre: "Meseros" },
    { Id: "25132", Nombre: "Bármanes" },
    { Id: "25141", Nombre: "Peluqueros" },
    { Id: "25142", Nombre: "Especialistas en tratamientos de belleza y afines" },
    { Id: "25151", Nombre: "Supervisores de mantenimiento y limpieza en oficias hoteles y otros establecimientos" },
    { Id: "25153", Nombre: "Conserjes y afines" },
    { Id: "25241", Nombre: "Modelos de modas, arte y publicidad" },
    { Id: "25242", Nombre: "Vendedores de mostradores tiendas y afines" },
    { Id: "25243", Nombre: "Vendedores puerta a puerta" },
    { Id: "25244", Nombre: "Vendedores a través de medios tecnológicos" },
    { Id: "25246", Nombre: "Vendedores de comidas en mostrador" },
    { Id: "25249", Nombre: "Otros vendedores no clasificados en grupos primarios" },
    { Id: "26113", Nombre: "Agricultores y trabajadores de huertas invernaderos viveros y jardines" },
    { Id: "26114", Nombre: "Agricultores y trabajadores calificados de cultivos mixtos" },
    { Id: "26121", Nombre: "Criadores de ganado y de la cría de animales domésticos, excepto aves de corral" },
    { Id: "26122", Nombre: "Avicultores y trabajadores calificados de la avicultura, incluye aves de corral" },
    { Id: "26123", Nombre: "Criadores y trabajadores calificados de la apicultura y la sericultura" },
    { Id: "26129", Nombre: "Criadores y trabajadores pecuarios calificados, avicultores y criadores de insectos no clasificados en otros grupos primarios." },
    { Id: "26130", Nombre: "Productos y trabajadores calificados e explotaciones agropecuarias mixtas cuya producción se destina al mercado. (siembra y cosechas de campo, recolección de cosechas etc)" },
    { Id: "26221", Nombre: "Trabajadores de explotación de acuicultura" },
    { Id: "27311", Nombre: "Reparación de instrumentos de precisión incluye relojeros y joyeros" },
    { Id: "27312", Nombre: "Fabricantes y afinadores de instrumentos musicales" },
    { Id: "27314", Nombre: "Alfareros y ceramistas" },
    { Id: "27316", Nombre: "Rotulistas, pintores decorativos y grabadores" },
    { Id: "27321", Nombre: "Preimpresores y afines" },
    { Id: "27322", Nombre: "Impresores" },
    { Id: "27323", Nombre: "Encuadernadores y afines" },
    { Id: "27331", Nombre: "Tejedores con telares" },
    { Id: "27332", Nombre: "Tejedores con agujas" },
    { Id: "27333", Nombre: "Otros tejedores" },
    { Id: "27341", Nombre: "Cestero mimbreros" },
    { Id: "27342", Nombre: "Sombrereros artesanales" },
    { Id: "27370", Nombre: "Artesanos del cuero" },
    { Id: "27391", Nombre: "Artesanos del papel" },
    { Id: "27511", Nombre: "Carniceros pescaderos y afines" },
    { Id: "27512", Nombre: "Panaderos, Pastelero y confiteros" },
    { Id: "27513", Nombre: "Operarios de la elaboración de productos lácteos" },
    { Id: "27514", Nombre: "Operarios de la conservación de frutas legumbre verduras y afines" },
    { Id: "27531", Nombre: "Sastres, modistos peleteros y sombrereros" },
    { Id: "27532", Nombre: "Patronistas y cortadores de tela cuero y afines" },
    { Id: "27533", Nombre: "Costureros bordadores y afines" },
    { Id: "27534", Nombre: "Tapiceros colchoneros y afines" },
    { Id: "27549", Nombre: "Trabajadores que realizan arreglos florales" },
    { Id: "29121", Nombre: "Lavanderos y planchador a mano" },
    { Id: "29129", Nombre: "Otro personal de limpieza no clasificados en otros grupos primarios ( limpiador de piscinas, limpiador de alfombras, drenajes)" },
    { Id: "29321", Nombre: "Empacadores manuales" },
    { Id: "29334", Nombre: "Surtidores de estanterías" },
    { Id: "29626", Nombre: "Lectores de medidores" },
    { Id: "29629", Nombre: "Otros ocupaciones elementales no clasificados en otros grupos primarios (acomodadores de espectáculos públicos, guardarropas etc)" },
    { Id: "32131", Nombre: "Biólogo, epidemiólogo, botánico, zoólogo y afines" },
    { Id: "32133", Nombre: "Profesionales de la protección medio ambiental" },
    { Id: "32141", Nombre: "Ingenieros Industriales y de producción" },
    { Id: "32144", Nombre: "Ingenieros Mecánicos, aeronáutico, automotriz, diseñador de motores." },
    { Id: "32148", Nombre: "Ingenieros catastrales, topógrafos, geodestas y afines" },
    { Id: "32149", Nombre: "Ingeniero textil, ingeniero de seguridad." },
    { Id: "32211", Nombre: "Médico general, medico clínico" },
    { Id: "32212", Nombre: "Médicos especialistas" },
    { Id: "32261", Nombre: "Odontólogos" },
    { Id: "32262", Nombre: "Farmacéuticos" },
    { Id: "32263", Nombre: "Profesionales de seguridad y salud en el trabajo, higiene laboral y ambiental" },
    { Id: "32264", Nombre: "Fisioterapeutas" },
    { Id: "32265", Nombre: "Dietista, y nutricionista" },
    { Id: "32266", Nombre: "Fonoaudiólogos y terapeutas" },
    { Id: "32267", Nombre: "Optómetras" },
    { Id: "32269", Nombre: "Otros profesionales de la salud no clasificados en otros grupos primarios" },
    { Id: "33132", Nombre: "Operadores incineradores instalaciones de tratamiento de agua y afines" },
    { Id: "33139", Nombre: "Técnicos en control de procesos no clasificados en otros grupos primarios" },
    { Id: "33211", Nombre: "Operadores audiométricos, de escáner óptico y afines" },
    { Id: "33251", Nombre: "Higienista asistentes odontológicos dental" },
    { Id: "33256", Nombre: "Asistente médicos ( asistente clínico, oftálmico, técnicos de transfusiones)" },
    { Id: "33257", Nombre: "Inspectores de seguridad, salud en el trabajo , medio ambiental y afines" },
    { Id: "33258", Nombre: "Técnicos en atención pre hospitalaria (Paramédico)" },
    { Id: "33259", Nombre: "Otros técnicos y profesionales del nivel de la salud no clasificados en otros grupos primarios ( consejeros de terapia de familia, planificación familiar, VIH)" },
    { Id: "33431", Nombre: "Camarógrafo, fotógrafo, operador equipos de grabación de sonido" },
    { Id: "33432", Nombre: "Diseñadores y decoradores de interiores" },
    { Id: "33433", Nombre: "Técnicos en galerías de artes museos y bibliotecas" },
    { Id: "33434", Nombre: "Chef de cocina" },
    { Id: "35120", Nombre: "Cocineros, Parrillero asador de carnes" },
    { Id: "35163", Nombre: "Personal de servicios funerarios y embalsamadores" },
    { Id: "35169", Nombre: "Otros trabajadores de servicios personales tales como acompañantes, trabajadores sexuales, damas de compañía, gigoló, prostitutas." },
    { Id: "35211", Nombre: "Vendedores en kioscos y puestas de mercado" },
    { Id: "35212", Nombre: "Vendedores ambulantes de alimentos preparados para consumo inmediato" },
    { Id: "35329", Nombre: "Trabajadores de los cuidados personales en servicios de salud, auxiliares del área de la salud." },
    { Id: "36111", Nombre: "Agricultores y trabajadores de cultivos extensivos" },
    { Id: "36112", Nombre: "Agricultores y trabajadores de plantaciones de árboles y arbustos" },
    { Id: "36122", Nombre: "Avicultores y trabajadores calificados de la avicultura" },
    { Id: "36310", Nombre: "Trabajadores agrícolas de subsistencia" },
    { Id: "36320", Nombre: "Trabajadores pecuarios de subsistencias" },
    { Id: "36330", Nombre: "Trabajadores agropecuarios de subsistencia ( recolecta frutas y plantas silvestres)" },
    { Id: "36340", Nombre: "Pescadores cazadores tramperos y recolectores de subsistencia" },
    { Id: "37113", Nombre: "Labrantes trozadores y grabadores de piedra" },
    { Id: "37115", Nombre: "Carpinteros de armar y de obra blanca" },
    { Id: "37122", Nombre: "Enchapadores, parqueteros y colocadores de suelos" },
    { Id: "37123", Nombre: "Revocadores" },
    { Id: "37124", Nombre: "Instaladores de material aislante e insonorización" },
    { Id: "37126", Nombre: "Fontanero de instaladores de tuberías" },
    { Id: "37213", Nombre: "Chapistas y caldereros" },
    { Id: "37215", Nombre: "Aparejadores y espalmadores de cables" },
    { Id: "37221", Nombre: "Herreros y forjadores" },
    { Id: "37222", Nombre: "Herramientitas y afines ( fabricantes de herramientas de mano, artículos de ferretería)" },
    { Id: "37223", Nombre: "Ajustadores y operadores de máquinas de herramientas" },
    { Id: "37224", Nombre: "Pulidores de metales y afiladores de herramientas" },
    { Id: "37231", Nombre: "Mecánicos y reparadores de vehículos automotores" },
    { Id: "37232", Nombre: "Mecánicos y reparadores se sistemas y motores de aeronaves" },
    { Id: "37233", Nombre: "Mecánicos y reparadores de máquinas agrícolas e industriales" },
    { Id: "37234", Nombre: "Reparadores e bicicletas y afines" },
    { Id: "37315", Nombre: "Sopladores, moldeadores, laminadores cortadores y pulidores de vidrio" },
    { Id: "37351", Nombre: "Tallador de piezas artesanales de madera" },
    { Id: "37352", Nombre: "Decoradores de piezas artesanales de madera" },
    { Id: "37361", Nombre: "Joyeros" },
    { Id: "37362", Nombre: "Orfebres y plateros" },
    { Id: "37363", Nombre: "Bisutero" },
    { Id: "37392", Nombre: "Artesanos del hierro y otros metales" },
    { Id: "37393", Nombre: "Artesanos de semillas y cortezas vegetales" },
    { Id: "37399", Nombre: "Artesanos de otros materiales no clasificados en otros grupos primarios ( tela, parafina, jabón, cuerno, cera, etc.)" },
    { Id: "37411", Nombre: "Electricistas de obra y afines" },
    { Id: "37412", Nombre: "Ajustadores electricistas incluye reparación de aparatos de uso doméstico." },
    { Id: "37413", Nombre: "Instaladores y reparadores de líneas eléctricas" },
    { Id: "37421", Nombre: "Ajustadores e instaladores en electrónica" },
    { Id: "37422", Nombre: "Instaladores y reparadores en tecnologías de la información y las comunicaciones" },
    { Id: "37516", Nombre: "Preparadores y elaboradores de cigarrillos y productos del tabaco" },
    { Id: "37521", Nombre: "Operarios del tratamiento de la madera" },
    { Id: "37522", Nombre: "Ebanistas y Carpinteros" },
    { Id: "37523", Nombre: "Ajustadores y operadores de máquinas para trabajar madera" },
    { Id: "37536", Nombre: "Zapatero, y afines" },
    { Id: "37713", Nombre: "Fabricante de quesos, lácteos" },
    { Id: "38160", Nombre: "Trabajadores con máquinas para elaborar alimentos y productos afines" },
    { Id: "39122", Nombre: "Lavador de autos, vehículos" },
    { Id: "39214", Nombre: "Trabajadores de jardinería y horticultura" },
    { Id: "39329", Nombre: "Ayudante de elaboración e alimentos y bebidas" },
    { Id: "39333", Nombre: "Trabajdores de carga (Bracero, coteros, estibadores cargadores de camiones)" },
    { Id: "39412", Nombre: "Ayudante de cocina" },
    { Id: "39624", Nombre: "Acarreadores de agua y recolectores de leña" },
    { Id: "42151", Nombre: "Ingenieros electricistas eléctricos, electrónicos, de telecomunicaciones y afines" },
    { Id: "42152", Nombre: "Ingenieros electrónicos" },
    { Id: "42153", Nombre: "Ingenieros de telecomunicaciones" },
    { Id: "42212", Nombre: "Médico cirujano general, plástico , anestesiólogo." },
    { Id: "43134", Nombre: "Operadores de instalaciones de refinación de petróleo y gas natural" },
    { Id: "43135", Nombre: "Controladores de procesos de producción de metales" },
    { Id: "43151", Nombre: "Maquinistas en navegación" },
    { Id: "43152", Nombre: "Trabajadores de la navegación de buques y embarcaciones" },
    { Id: "43153", Nombre: "Pilotos de aviación y afines" },
    { Id: "43155", Nombre: "Técnicos en seguridad aeronáutica" },
    { Id: "44323", Nombre: "Trabajadores de servicios de transporte" },
    { Id: "45164", Nombre: "Instructores de conducción" },
    { Id: "45245", Nombre: "Vendedores de combustible incluye montallantero, cambiador de aceite, engrase y afines" },
    { Id: "46112", Nombre: "Agricultores y trabajadores calificados para plantaciones de arboles y arbustos (podador y recolector)" },
    { Id: "46210", Nombre: "Trabajador forestal calificados y afines" },
    { Id: "46222", Nombre: "Pescadores de agua dulce y en aguas costeras" },
    { Id: "46223", Nombre: "Pescadores de altamar" },
    { Id: "46224", Nombre: "Cazadores y tramperos" },
    { Id: "47127", Nombre: "Mecánicos montadores de aire acondicionado y refrigeración" },
    { Id: "47131", Nombre: "Pintores y empapeladores" },
    { Id: "47132", Nombre: "Barnizadores y afines" },
    { Id: "47212", Nombre: "Soldadores y oxicortadores" },
    { Id: "47535", Nombre: "Apelambradores, pellejeros y curtidores en tratamiento de pieles y pelos de animales" },
    { Id: "48311", Nombre: "Maquinistas de locomotoras" },
    { Id: "48312", Nombre: "Guardafrenos, guardagujas y agentes de maniobras" },
    { Id: "48321", Nombre: "Conductores de motocicletas" },
    { Id: "48323", Nombre: "Conductores de camionetas y vehículos livianos" },
    { Id: "48324", Nombre: "Conductores de taxis" },
    { Id: "48331", Nombre: "Conductores de buses microbuses y tranvías" },
    { Id: "48332", Nombre: "Conductores de camiones y vehículos pesados" },
    { Id: "48341", Nombre: "Trabajadores de maquinaria agrícola y forestal móvil" },
    { Id: "48343", Nombre: "Trabajadores de grúas aparatos elevadores y afines" },
    { Id: "48344", Nombre: "Operadores de montacargas" },
    { Id: "49331", Nombre: "Conductores de vehículos accionado a pedal o a brazo" },
    { Id: "49621", Nombre: "Mensajeros mandaderos maleteros y repartidores" },
    { Id: "49622", Nombre: "Personas que realizan trabajos varios" },
    { Id: "52142", Nombre: "Ingenieros civiles." },
    { Id: "52143", Nombre: "Ingenieros medio ambientales" },
    { Id: "52144", Nombre: "Ingeniero marino" },
    { Id: "52145", Nombre: "Ingeniero químico" },
    { Id: "52146", Nombre: "Ingenieros de minas metalúrgicos y afines" },
    { Id: "52149", Nombre: "Ingeniero de tráfico, ingeniero de energía nuclear, ingeniero de salvamento marítimo." },
    { Id: "52161", Nombre: "Arquitectos constructores" },
    { Id: "52212", Nombre: "Médico especialista en medicina nuclear, médico radiólogo, médico patólogo forense." },
    { Id: "52212", Nombre: "Médico especialista en psiquiatría para atención de víctimas." },
    { Id: "52619", Nombre: "Profesionales en derecho no clasificados en otros grupos primarios que atienden víctimas" },
    { Id: "52635", Nombre: "Profesionales del trabajo social, consejeros, psicólogos para atención a víctimas" },
    { Id: "52659", Nombre: "Artistas creativos interpretativos no clasificados en otros grupos primarios incluye (Acróbata, equilibrista, trapecista, torero y otras ocupaciones relacionada con espectáculos públicos en actividades extremas)" },
    { Id: "53118", Nombre: "Delineante de arquitectura, dibujante técnico, con intervención directa en obras" },
    { Id: "53133", Nombre: "Controladores de instalaciones de procesamiento de productos químicos, filtración y separación de sustancia químicas, procesos químicos." },
    { Id: "53154", Nombre: "Controlador de tráfico aéreo y marítimo" },
    { Id: "53211", Nombre: "Radiólogo oral, operador de equipo audiométrico, de escáner óptico," },
    { Id: "53355", Nombre: "Detective privado" },
    { Id: "53421", Nombre: "Atletas y Deportistas (Deporte extremo )" },
    { Id: "54323", Nombre: "Controladores administrativos de tráfico aéreo" },
    { Id: "55411", Nombre: "Bomberos y rescatistas" },
    { Id: "55414", Nombre: "Escolta, guardaespaldas" },
    { Id: "57111", Nombre: "Constructores de Casas" },
    { Id: "57112", Nombre: "Albañiles" },
    { Id: "57114", Nombre: "Operarios en cemento armado enfoscadores y afines" },
    { Id: "57119", Nombre: "Oficiales de la construcción de obra gruesa y afines no clasificados en grupos primarios (demolición, reparación y mantenimiento de fachadas, armado de andamios, operarios de construcción edificios de gran altura)" },
    { Id: "57121", Nombre: "Techadores" },
    { Id: "57125", Nombre: "Cristaleros" },
    { Id: "57133", Nombre: "Limpiadores de fachadas, deshollinadores." },
    { Id: "57211", Nombre: "Moldeadores y macheros, fundición de metales" },
    { Id: "57212", Nombre: "Soldadores y oxicortadores ( cortan metales con gas o arco eléctrico)" },
    { Id: "57213", Nombre: "Chapistas caldereros horneros- exposición altas temperaturas" },
    { Id: "57214", Nombre: "Montadores de estructuras metálicas" },
    { Id: "57419", Nombre: "Personal de servicios de protección no clasificados en otros grupos primarios ( salvavidas, socorristas)" },
    { Id: "57541", Nombre: "Buzos" },
    { Id: "57544", Nombre: "Fumigadores y otros controladores de plagas y malas hierbas" },
    { Id: "57549", Nombre: "Trabajadores e oficios relacionados no clasificados en otros grupos primarios tales como los que manipulas juegos pirotécnicos." },
    { Id: "58342", Nombre: "Trabajadores de máquinas de movimientos de tierra construcciones de vías y afines" },
    { Id: "59123", Nombre: "Limpiadores de ventanas" },
    { Id: "59212", Nombre: "Clasificadores de desechos" },
    { Id: "59311", Nombre: "Trabajadores de minas y canteras" },
    { Id: "59312", Nombre: "Trabajadores de obras públicas y mantenimiento" },
    { Id: "59313", Nombre: "Trabajadores de la construcción" },
    { Id: "59313", Nombre: "Trabajadores de construcción, demolición, excavación" },
    { Id: "59333", Nombre: "Bracero, coteros, estibadores de embarcaciones aéreas, marítimas y/o fluviales" },
    { Id: "59611", Nombre: "Recolectores de basura y material reciclable" },
    { Id: "59613", Nombre: "Barrenderos y afines" }
]

export const occupationDecretoOptions: OccupationDecretoOption[] = occupationsDecretoData.map(item => ({
    code: item.Id,
    name: item.Nombre
}))