export { IndependienteConContratoForm } from "./components/independiente-con-contrato-form"
export { ListaRegistros } from "./components/lista-registros"
export { EnvioRegistro } from "./components/envio-registros"
export { IndependienteConContratoMassiveUpload } from "./components/massive-upload"
export { useRegistroStore } from "./stores/registro-store"
export type { Registro, IndependienteConContratoFormData, IndependienteConContrato } from "./types/independiente-types" 